# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='usuario',
            field=models.TextField(),
        ),
    ]
