# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20170601_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='usuario',
            field=models.TextField(),
        ),
    ]
