# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desde',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='para',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
