# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='año',
            new_name='ano',
        ),
    ]
