# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20170510_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='desde',
            name='firma',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
