# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_desde_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.TextField(),
        ),
    ]
