# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
