# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20170530_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmessage',
            name='dueno',
            field=models.IntegerField(null=True),
        ),
    ]
