# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alertmessage_dueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ant',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
